name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # Step 1
  build_app:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.x'
          channel: 'dev'

      - name: Build APK
      - run: flutter  config --enable-web
      - run: flutter  config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter build apk

      - name: Testing
      # Check for any formatting issues in the code.
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
      - run: flutter test

      - name: Create a Release APK
      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk